import javax.swing.JOptionPane;

public class animal {

    public static void main(String[] args) {

        // Keep Scrolling...
System.out.println("                                    .++`    .;.");
System.out.println("                                    :nz.    ,n#`");
System.out.println("                                  ,nW;    `z@;                   .;,");
System.out.println("                                `#@x.    ;WW:                `;#x+.");
System.out.println("                               :W#z`    +#W,              `in@W*`");
System.out.println("                              *@##    `z#@,            `;n@#Wi`");
System.out.println("                             +##+    `x#@:           .+W##Wi`");
System.out.println("                            +###    .M##i          ,z@##W*`");
System.out.println("                           ;##n`   .M##+         ,z###@+`");
System.out.println("                          .@#M`   .M##n        .#@###z.");
System.out.println("                          z#@,   `M##x`      `*@###x:");
System.out.println("                         ,##i   `x##W.      ,x###@*                                            ``...,..``");
System.out.println("                         ##n    ###@,      *@###n.                                  `,:i*#zxMW@#########@WMn+;.");
System.out.println("                        `W@.   i###i     .x###W;                          ,;*#znxMW##################@@@@@@@@@@x+,");
System.out.println("                        *#+   ,@###     :W###n`                      `;#x@###########@Wxz#*i;:,,..```````");
System.out.println("                       .@W`   x##x`    *###@i                     .*x@#########@Mz*;.`");
System.out.println("                       z#i   +##W.   `####M,                    ,z@######Wxz+;,`");
System.out.println("                      ,#M`  ,@##;   `z###z`                   .n#######z,");
System.out.println("                      n#i   x###   `n##@*                    *@#######z");
System.out.println("                     :#W`  i##M`  `x##W:                   ,x#########;");
System.out.println("                     n#*  `W#@,  `n##M,                  `+@##########z.");
System.out.println("                    .#@`  +##+  `n##x.                  .x##############Mz+*;,`");
System.out.println("                    +#z  .@#M` `z##z`                  :W#####################@xi.");
System.out.println("                   `W#:  z##:  ###+                   ;@#############Mi..:+x######Mz*:`");
System.out.println("                   ;#M  ,##z  *##*                    `,,:n###########W+.   .*x@######@Mzi.");
System.out.println("                   n#+  x#@` ;##*                          ,#@##########@#.    `in@########W+,");
System.out.println("                  `@#. :##* ,@##                             .+@##########@*`     `ix#########x;`");
System.out.println("                  i#x  x#W`.W#n`                               `*W####@M####Wi`      ,#W########Mi");
System.out.println("                  n#* ;##i`x#x`                                  `*W###*;W####Wi`       .;#x######x:");
System.out.println("                 `@#, M#M`z#W.                                     `+@##z.+@####M:          .+W#####n:");
System.out.println("                 ;#W i##+n##i     .:                                 :@##M`,x#####n.          `;x#####M*`");
System.out.println("                 z#W`W######`  `;n#*             .+:                  ,@##i  iW####@+`           .iz@###@#.");
System.out.println("                 W##########;+n@###n           `#@i   `;*i.            ;##n   `#@####W;             `;n@##@#`");
System.out.println("                .###################;     ,#  `x@;   iW##n.             z##,    .######z`              .#@##W;");
System.out.println("                ;###################@;   *@x  n#;  `z##x;               .@#n      :W####M.               .z###+");
System.out.println("                ######################* +##: *##  .M#Wi                  n##;      .x####W,                ,M###");
System.out.println("                x##########x+;;;#W####ii##+ ,@@` :@#M.                   i##W`      `#####@;                `+##z");
System.out.println("                @#######@#.      `z##M.@#x``M#n`####,                    ,###z        ;@###@i                 :W##");
System.out.println("               .#######n.         `M#;###:`n##W@###W                     `####:        :@####*                 .M#;");
System.out.println("               .#####@i            +n`@#@#W########@,         .          `####M         ,@####+                 `n@,");
System.out.println("                @###x.             +:i###############WMn*    .#@WMni:,``.######:`#`      ,W#####                  zW");
System.out.println("                M##n`              ` n###########@n*;,,.,.+#.i#########@#######+i#x`      +#####z`                 #");
System.out.println("                x#x`                :##########W*izMWW@@@###WM#################@@##z      `######n`");
System.out.println("                nW.                ,W#########x.x###################################i       ,M####x`");
System.out.println("                zi             `z;*@#########x.z#############################@#x####W`        *@###n`");
System.out.println("                *              i#M##########@:M#################M+iii+#nMMM+,` `*#####         .n###z");
System.out.println("                               #############z####x##x@#########xinz+:`           z###@.          i@##+");
System.out.println("                               z############;n###    `#########i+####W*`         `W####           :@##;");
System.out.println("                               z###########W.:@#M,   +#@#####@#*i######W;         :###@`           ,W#@,");
System.out.println("                               ############`  .+n#   *W######Wz#,########x.        ####+            ,W#M`");
System.out.println("                               +#########x            `x######i:`@########n`       `W##W             ,@##");
System.out.println("                               ##########:             i######W, x#########M,       ;###:             ;##;");
System.out.println("                              `W####@W##@              `@######W,+##########@;       x###              +#W`");
System.out.println("                              *#####M`.#n               ########,.@@@@#######@;      :##M               x#+");
System.out.println("                              M######iWz...             `W#####W  `  `,in#####@,      x#@               ,#M");
System.out.println("                             `#######x*#M:@#             ,@####W         ;W####W`     ;##.               z#`");
System.out.println("                             .########,W#zn#+ *.          :W####.  :nWWx: .W#####     `W#,               ,#,");
System.out.println("                             .########*+##*#@,*M`          .z###+ ;@####@* ,@###@:     ##,                M,");
System.out.println("                             .########x*##zx#n.#;            .+xM`W#######z`:@###x     :#`                z`");
System.out.println("                              @#######@W##@###i@z               `:#########n`i####;    `M                 ;`");
System.out.println("                              x############M####M                *##########z ####x     ;");
System.out.println("                              +##################`               +###########i`M###:");
System.out.println("                              ,##################:               *###########@.;###n");
System.out.println("                               ##################z               ;########@xx@# W###:");
System.out.println("                               `x################@:              .@#######:  `i`z###n");
System.out.println("                                .W################@,             +#######@  .zzi####@`");
System.out.println("                                 ,@#################            `M`M######: i########;");
System.out.println("                            *`    ,@###############@`           `@`,@#####x ,@########");
System.out.println("                            *M:    :@#######+#@#####.            @+ ,W#####n.;W######x");
System.out.println("                             +#xi,`.z#######: ,M###n  .`         W@; .n#####@; ,i+M##W");
System.out.println("                              M#############@xM@###@+.#W.        M#@*` ;x####W:   ;###`");
System.out.println("                              ,zM@######################n        W###x`,:,+x@##M+,`###.");
System.out.println("                                 .######################@.      ,####zn##+` .;,:;, M##,");
System.out.println("                                 ,++ii+@############x####;      z####+n###@W##M@#+ x##:");
System.out.println("                                       ;@##M*@z#####i####;     `@####+ n########@, n##:");
System.out.println("                                        *##M.. z@###@###@`     ;#####z  ,:;x###@;  n##;");
System.out.println("                                        `##@*  `z######@;      z###### ,nzn@###;   x##;");
System.out.println("                                         x##W  `x:Wx@#x:       W#####; z###M##x    M##;");
System.out.println("                                         i##@`    : `,        `#####W `@#M#`;#x    @##:");
System.out.println("                                         `@##x,               ,#####i :@;  ###@   ,###,");
System.out.println("                                          *####Wi             :####M` ;i   x##*   *##@");
System.out.println("                                           z####`             ;####i  `    z#+    x##n");
System.out.println("                                            ,:.               :###@`       :@    ,###*");
System.out.println("         ___________________________________^_______          ,###n         +`   n###,");
System.out.println("         |                                          |         .####            .####M");
System.out.println("         |  My armor is like tenfold shields,       |          @##+          `M#####+");
System.out.println("         |  my teeth are swords, my claws spears,   |          M###          :######,");
System.out.println("         |  the shock of my tail a thunderbolt,     |          n##n          +#####x");
System.out.println("         |  my wings a hurricane,                   |          +##W          n#####i");
System.out.println("         |  and my breath death!                    |          .###.        `@####M");
System.out.println("         |                                          |           n##;        z#####:");
System.out.println("         |__________________________________________|           .@##      `z#####+");
System.out.println("                                                                 +#M     .x#####z");
System.out.println("                                                                 `W@    :W#####n`");
System.out.println("                                                                `;i#.  ;@######`");
System.out.println("                                                                `M`@, :@#####+");
System.out.println("                                                                :@`x,`W####@i");
System.out.println("                                                        `in,    ##;*`*####W:");
System.out.println("                                                      .#W##i   ,@#M` ###@#`");
System.out.println("                                                    ,n#####,  ;W###M`.z*.");
System.out.println("                                                  :n#######`in#####M");
System.out.println("                                                ,n######Wi`########x");
System.out.println("                                              .z######Mi` ,###zz###W");
System.out.println("                                             i@#####n:    ###i;##M@#:");
System.out.println("                                            ######n,      xx:`M##.W##");
System.out.println("                                           z####@;        x, :##W`@#x");
System.out.println("                                          #####x.         ;  *#M,;##*");
System.out.println("                                         ;####@.             +#, ##i");
System.out.println("                                        `W####;              *x  nx");
System.out.println("                                        #####+               ,*  n#");
System.out.println("                                       .@###x`                `  *i");
System.out.println("                                       ####@.");                                                       
System.out.println("                                      `@####");
System.out.println("                                      ;####.");
System.out.println("                                      +###W");
System.out.println("                                      z###M");
System.out.println("                                      ####W");
System.out.println("                                      ;####`");
System.out.println("                                      `@###*");
System.out.println("                                       z###W.");
System.out.println("                                       ,@###x`");
System.out.println("                                        +####W:");
System.out.println("                                        `M#####n,");
System.out.println("                                         .M######M*.");
System.out.println("                                          .M########x+:`");
System.out.println("                                           `z##########@z;`");
System.out.println("                                             ;W###########W*`");
System.out.println("                                               ;zW@#########W;");
System.out.println("                                                  ``,;+x@#####n.");
System.out.println("                                                        `ix####W:");
System.out.println("                                                           :x###@;");
System.out.println("                                                             ;W##@:");
System.out.println("                                                              `z##@.");
System.out.println("                                                                *##x"); 
System.out.println("                                                                 ;@#i");                 
System.out.println("                                                                  ;@M");
System.out.println("                                                                   i#,");
System.out.println("                                                                    z+");
System.out.println("                                                                    `#");        
System.out.println("                                                                     .\n\n\n\n\n");
System.out.println("nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnnnzzzzzzz#zznnnnz*i:::;i+znnnnnnnnnnnnnnnz#+;;:::::;i+znnnnnnnnnnnnnnnnnnnz+i;:::::;i#znnnnnnnnnnnnnnnnnnnnz#*;:::::;i+znnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnn+,,,,,,,,,inn#i.`      `,*nnnnnnnnnnnn#i:.``       ``.;+nnnnnnnnnnnnnnn+;,``       `.,i#nnnnnnnnnnnnnnnn+i,``       ``,;#nnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnni        `*x+,           `innnnnnnnnzi.                `iznnnnnnnnnnn#:`               .*nnnnnnnnnnnnn#;.               .iznnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnz:        `#*`             `*nnnnnnn#,`          `       `;znnnnnnnnz;`                  `;nnnnnnnnnnzi.                   :znnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnnz.        `:`               ,nnnnnn#,                     `*xnnnnnn#:`                    `innnnnnnnz:`                    `:nnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnn#.                          `+nnnnz:          ``           ,nnnnnnz,                       `+nnnnnnz:`                      `*nnnnnnnnnnnnn");
System.out.println("nnnnnnnnnnn*`                           innnn*`        `:**i.       ` .znnnnz:                     `   :nnnnnn:`                     `  ,znnnnnnnnnnnn");
System.out.println("nnnnnnnnnnni`                           ;xnnn.         inxxx#`        `#nnxn;`          .,,.           .zxnnxi`          .,:,`          `#nnnnnnnnnnnn");
System.out.println("nnnnnnnnnnn:         `  ``.`            ;xnn#`        `+xxxxn,..`..```.#xnn*`         `i#nnz;`         `#nnnz`         `:#nnni`         `*xnnnnnnnnnnn");
System.out.println("nnnnnnnnnnz,         ``,+zn#:``         ;nnn*``        ,+nxxxnnnnnnnnnnnxnz,          inxxnxz.          *nnn;          ;nxxxxx,          innnnnnnnnnnn");
System.out.println("nnnnnnnnnn#.        ``:nxnnxz.          ixnxi           ``:*#zxnxxxnnnnnxx*          :nxxnnnn;          +nn#``        ,nxxxnxn;``        ;nnnnnnnnnnnn");
System.out.println("nnnnnnnnnn#`         `#xnnnnn:          *xnni               `.,*znxxnnnxnn:         `#xxnnnxn*::::::::::#nx;         `ixnnnnnn+::::::::::*nnnnnnnnnnnn");
System.out.println("nnnnnnnnnn*`         :nxnnnnn,`        `+xnn+`                  `,*nxnnnnz.         .xxnnnnnnxxxxxxxxxxxxnn.         .zxnnnnnnnxxxxxxxxxxnxnnnnnnnnnnn");
System.out.println("nnnnnnnnnxi          *nxxnnnn,         `zxxnn.                     ,#xnnn*`         ;xnxnnnnnnnnnxxxxxxnnx#`         :nxnnxnnnnnnnnxxxxxnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnn:          znxxxxxz.         .nxnnx+.                     .#xxn;          +xnxnnnnnnnnnnnnnnnnnx*          innnnxnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnnnnnnnn,         `nxnxxxn+`         :nnnnnx*.`                    :zxn:         `#nxnnnnnnnnnnnnnnnnnxn;         `*xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn");
System.out.println("nnnxxxnnxz.        `.nxnnnnn*`         ;xnnnxnxzi,``                ``#xn,         .zxnnnnnnnnnnnxxxxxxnnx,         `+xnnxnnnnnxxxxxxxnnnnnnnnnnnnnnnn");
System.out.println("nnxxnnnnn#         `:nxxxnxni          *xxnnnnnxxn#i:,```            `*xz.`        .nxxnnnnx#++++++++++zxx,         `+xxnnnxxz+++++++#++znnnnnnnnnnnnn");
System.out.println("nnxxnnnnn+          ixnxxxxn;         `+xxnxxnnxxxxxnz#*;,`          `inz.         .znxnnxxn:``````````+xx,         `+xxnxxnn;`````````.*nnxnnnnnnnnnn");
System.out.println("nnxxnnnnni         `+xnxxxxz,         .zxnzzzzz#zzzznxxxnzi`         `*xn,         `*xnxnnn+`         ,nnx:          ixnxxnx#.         `#nnnxnnnnnnnnn");
System.out.println("nnxxnnnxn:         `zxxnxxxz`         ,nx#.````````.+xxxxnn,         `#xn:          ,zxxxx+.          *xxx;          .#xxxx#,`         :xxxnnxnxxnnnnn");
System.out.println("nnxxnnnxz,         `nxxnxxx#`         :nxz.        `ixxnxx#.         :nnxi           ,*#+;.          .zxxx+`          ,*#+*,`         .#xxnxnnnnnnnnnn");
System.out.println("nnxnnnxx#.         ,xxxxxxx*`         ixxz.         .*nnn+:         `*xxx#.           `.`           `*xxxxz.           ````          `ixxxxnnnnnnnnnnn");
System.out.println("nxxxnnxx+`         ;xxxxnxx;          +xxx,          `.,.`          :nxxxn;          `             `;nxxxxxi                       ` :nxxxxnxxxxxxxxxx");
System.out.println("nnxxnnnx*          ixxxxnxn:         `#xxx+`           `           ,zxxnxxz.                      `inxxxxxxn:                      `:zxxxxxnnnnnnnnnnn");
System.out.println("nxxxxnnn;         `+xxxxnnz.         .zxxxn:                      ,#xxxnxxx+.                    `;nxxxxnxxxz,                    `;zxxxxxxxxxxxxxxxxx");
System.out.println("xxxxxxxn,         `#xxxxxxz`         ,nxxxxz:`          `       `;zxxxxxxxxx+,      `           .*nxxxxxnxxxx#,          `       .*nxxxxxxxxxxxxxxxxxx");
System.out.println("xxxxxxxz.         .nxxxxxx#          :nxxxxxn*.              `.;#xxxxxxxxxxxxzi.             `,*zxxxxxxxxxxxxxn*,`            `,izxxxxxxxxxxxxxxxxxxxx");
System.out.println("xxxxxxxn+*********+xxxxnxxz**********#xxxxxxxxz+;,..`````..:;+znxxxxxxxxxxxxxxnz*:..`````..:i+nxxxxxxxxxxxxxxxxxn+;,.`````..,i#nxxxxxxxxxxxxxxxxxxxxxx");
System.out.println("xxxxxxnxnxxxxxxxxxxxxxxnxnxxxxxxxxxxxxxxxxxxxxxxnnz#+++##zznnxxxxxxxxxxxxxxxxxxxxnzz#+++#znnxxxxxxxxxxxxxxxxxxxxxxxnz#+++##znxxxxxnxxxxxxxxxxxxxxxxxxx");
System.out.println("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxnxxnxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
System.out.println("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
System.out.println("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
System.out.println("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
}

    
}